# ============================================
# RAG PIPELINE - HYBRID VERSION
# Generative answers via Groq (free API) when available
# Falls back to 100% local extractive method if API fails
# ============================================

import os
import re
from dotenv import load_dotenv
from document_loader import load_document
from chunker import create_chunks
from embedder import load_embedding_model, create_embeddings, get_query_embedding
from vector_store import (
    create_vector_store,
    save_vector_store,
    load_vector_store,
    search_similar_chunks
)

load_dotenv()

# Groq client setup — wrapped so a missing/invalid key never crashes the app
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
groq_client = None

if GROQ_API_KEY:
    try:
        from groq import Groq
        groq_client = Groq(api_key=GROQ_API_KEY)
    except Exception as e:
        print(f"Groq client could not be initialized: {e}")
        groq_client = None


def initialize_pipeline():
    print("Starting DocuMind pipeline...")
    model = load_embedding_model()
    print("Pipeline is ready!")
    return model


def process_document(file_path, model):
    print(f"\nProcessing document: {file_path}")

    text = load_document(file_path)
    if not text:
        print("Error: Failed to load document!")
        return False

    chunks = create_chunks(text)
    embeddings = create_embeddings(chunks, model)
    index = create_vector_store(embeddings, chunks)
    save_vector_store(index, chunks)

    print("\nDocument processed successfully!")
    return True


def extract_best_sentences(question, chunks, embedder_model, top_n=3):
    """
    Splits each chunk into sentences and calculates the similarity
    between the question and each sentence.

    Returns the most relevant sentences.

    This follows an extractive RAG approach where answers are
    directly extracted from the document instead of being
    generated by a language model.
    """

    all_sentences = []

    for chunk in chunks:
        sentences = re.split(r'(?<=[.!?])\s+', chunk)

        for s in sentences:
            s = s.strip()
            if len(s) > 15:
                all_sentences.append(s)

    if not all_sentences:
        return chunks[:1]

    question_embedding = get_query_embedding(question, embedder_model)
    sentence_embeddings = embedder_model.encode(
        all_sentences,
        convert_to_numpy=True
    )

    import numpy as np

    q_norm = question_embedding / np.linalg.norm(question_embedding)

    scores = []

    for i, sent_emb in enumerate(sentence_embeddings):
        s_norm = sent_emb / np.linalg.norm(sent_emb)
        similarity = np.dot(q_norm, s_norm)
        scores.append((similarity, all_sentences[i]))

    scores.sort(key=lambda x: x[0], reverse=True)
    top_sentences = [s for score, s in scores[:top_n]]

    return top_sentences


def get_extractive_answer(question, context_chunks, embedder_model=None):
    """
    Generates an answer using the local extractive approach.
    No external API calls are required. Used as the default
    mode and as a fallback if the generative API is unavailable.
    """

    if embedder_model is None:
        return context_chunks[0] if context_chunks else "No answer found."

    best_sentences = extract_best_sentences(
        question,
        context_chunks,
        embedder_model,
        top_n=3
    )

    if not best_sentences:
        return "No relevant answer found in the document."

    answer = " ".join(best_sentences)
    return answer


def get_generative_answer(question, context_chunks):
    """
    Generates a natural-language answer using Groq's free API,
    grounded strictly in the retrieved context chunks (RAG).

    Returns None if the API call fails for any reason, so the
    caller can fall back to the extractive method instead.
    """

    if groq_client is None:
        return None

    context = "\n\n".join(context_chunks)

    prompt = f"""Answer the question using ONLY the context below.
If the answer is not present in the context, say "I don't know based on the provided document."
Keep the answer concise and natural.

Context:
{context}

Question: {question}

Answer:"""

    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2,
            max_tokens=300,
        )
        return response.choices[0].message.content.strip()

    except Exception as e:
        print(f"Groq API call failed, falling back to extractive answer: {e}")
        return None


def get_ai_answer(question, context_chunks, embedder_model=None, mode="auto"):
    """
    Generates an answer for the user's question.

    mode:
      - "auto"       : try generative (Groq) first, fall back to extractive
      - "generative" : force generative, return error message if API unavailable
      - "extractive" : force the original local-only method (no API call)
    """

    if not context_chunks:
        return "No relevant answer found in the document."

    if mode == "extractive":
        return get_extractive_answer(question, context_chunks, embedder_model)

    if mode in ("auto", "generative"):
        generative_answer = get_generative_answer(question, context_chunks)

        if generative_answer:
            return generative_answer

        if mode == "generative":
            return "Generative mode is currently unavailable. Please try again or switch to extractive mode."

        # mode == "auto" and Groq failed -> silently fall back
        return get_extractive_answer(question, context_chunks, embedder_model)

    # Unknown mode safeguard
    return get_extractive_answer(question, context_chunks, embedder_model)


def ask_question(question, model, mode="auto"):
    print(f"\nQuestion: {question}")

    index, chunks = load_vector_store()

    if index is None:
        print("Please upload a document first!")
        return None

    query_embedding = get_query_embedding(question, model)

    similar_chunks = search_similar_chunks(
        query_embedding,
        index,
        chunks,
        top_k=3
    )

    if not similar_chunks:
        return None

    context_chunks = [result["chunk"] for result in similar_chunks]

    answer = get_ai_answer(
        question,
        context_chunks,
        embedder_model=model,
        mode=mode
    )

    return {
        "question": question,
        "answer": answer,
        "sources": similar_chunks
    }