# ============================================
# RAG PIPELINE - RELIABLE LOCAL VERSION
# No external API needed - 100% free, always works!
# ============================================

import os
import re
from dotenv import load_dotenv
from document_loader import load_document
from chunker import create_chunks
from embedder import load_embedding_model, create_embeddings, get_query_embedding
from vector_store import (
    create_vector_store,
    save_vector_store,
    load_vector_store,
    search_similar_chunks
)

load_dotenv()


def initialize_pipeline():
    print("Starting DocuMind pipeline...")
    model = load_embedding_model()
    print("Pipeline is ready!")
    return model


def process_document(file_path, model):
    print(f"\nProcessing document: {file_path}")

    text = load_document(file_path)
    if not text:
        print("Error: Failed to load document!")
        return False

    chunks = create_chunks(text)
    embeddings = create_embeddings(chunks, model)
    index = create_vector_store(embeddings, chunks)
    save_vector_store(index, chunks)

    print("\nDocument processed successfully!")
    return True


def extract_best_sentences(question, chunks, embedder_model, top_n=3):
    """
    Splits each chunk into sentences and calculates the similarity
    between the question and each sentence.

    Returns the most relevant sentences.

    This follows an extractive RAG approach where answers are
    directly extracted from the document instead of being
    generated by a language model.
    """

    # Extract all sentences from the retrieved chunks
    all_sentences = []

    for chunk in chunks:
        # Split chunk into sentences using regex
        sentences = re.split(r'(?<=[.!?])\s+', chunk)

        for s in sentences:
            s = s.strip()

            # Skip very short sentences
            if len(s) > 15:
                all_sentences.append(s)

    if not all_sentences:
        return chunks[:1]

    # Generate embeddings for question and sentences
    question_embedding = get_query_embedding(question, embedder_model)
    sentence_embeddings = embedder_model.encode(
        all_sentences,
        convert_to_numpy=True
    )

    # Calculate cosine similarity
    import numpy as np

    q_norm = question_embedding / np.linalg.norm(question_embedding)

    scores = []

    for i, sent_emb in enumerate(sentence_embeddings):
        s_norm = sent_emb / np.linalg.norm(sent_emb)
        similarity = np.dot(q_norm, s_norm)
        scores.append((similarity, all_sentences[i]))

    # Select top-ranked sentences
    scores.sort(key=lambda x: x[0], reverse=True)
    top_sentences = [s for score, s in scores[:top_n]]

    return top_sentences


def get_ai_answer(question, context_chunks, embedder_model=None):
    """
    Generates an answer using a local extractive approach.

    No external API calls are required.
    """

    if embedder_model is None:
        # Fallback if embedding model is unavailable
        return context_chunks[0] if context_chunks else "No answer found."

    # Retrieve the most relevant sentences
    best_sentences = extract_best_sentences(
        question,
        context_chunks,
        embedder_model,
        top_n=3
    )

    if not best_sentences:
        return "No relevant answer found in the document."

    # Combine selected sentences into a final answer
    answer = " ".join(best_sentences)

    return answer


def ask_question(question, model):
    print(f"\nQuestion: {question}")

    index, chunks = load_vector_store()

    if index is None:
        print("Please upload a document first!")
        return None

    query_embedding = get_query_embedding(question, model)

    similar_chunks = search_similar_chunks(
        query_embedding,
        index,
        chunks,
        top_k=3
    )

    if not similar_chunks:
        return None

    context_chunks = [result["chunk"] for result in similar_chunks]

    # Generate answer using local extractive RAG
    answer = get_ai_answer(
        question,
        context_chunks,
        embedder_model=model
    )

    return {
        "question": question,
        "answer": answer,
        "sources": similar_chunks
    }
